#!/bin/bash
if test -e "$HOME"/.config/leftwm/default_apps.sh;
then
  source $HOME/.config/leftwm/default_apps.sh;
else
  export TERM=alacritty
  export BROWSER=firefox
  export DOC=libreoffice
  export FILE=dolphin
  export PLAYER=vlc
  export GAME=steam
  export PHOTO=gimp
  export SANDBOX=virtualbox
  export DEV="alacritty -e vim";
fi


TAG=$(leftwm-state -q -w 0 -t "$HOME"/.config/leftwm/themes/current/name.liquid)

case "$TAG" in 
  1) $TERM &> /dev/null ;;
  2) $BROWSER &> /dev/null ;;
  3) $DOC &> /dev/null ;;
  4) $FILE &> /dev/null ;;
  5) $PLAYER &> /dev/null ;;
  6) $GAME &> /dev/null ;;
  7) $PHOTO &> /dev/null ;;
  8) $SANDBOX &> /dev/null ;;
  9) $DEV &> /dev/null ;;
esac
