#!/bin/bash

SCRIPTPATH="$( cd "$(dirname "$0")" || return ; pwd -P )"

#set background
if [ -x "$(command -v feh)" ]; then
  feh --no-fehbg --bg-fill "$SCRIPTPATH"/down.jpg
fi

echo "UnloadTheme" > "$XDG_RUNTIME_DIR"/leftwm/commands.pipe

pkill compton
pkill picom
pkill polybar
pkill dunst
#pkill xss-lock
